sonar.projectKey=MiBanquito
sonar.projectName=MiBanquito
sonar.projectVersion=1.0

sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/test_*.py,**/*_test.py

sonar.python.coverage.reportPaths=reports/coverage.xml
sonar.python.xunit.reportPath=reports/test-results.xml

sonar.exclusions=**/venv/**,**/__pycache__/**
sonar.sourceEncoding=UTF-8